# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Determine Docker Image Tag
      id: docker_tag
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          echo "::set-output name=TAG::commit-${{ github.sha }}"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "::set-output name=TAG::pr-${{ github.event.pull_request.number }}"
        fi

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: arunkumar611/all
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: githubactions_gradle_docker
   
         
